config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'
  resources :stories
  get '/random', to: 'stories#random'

end

app/models/story.rb
class Story < ActiveRecord::Base

  def self.scrap

  end

  def fetch_stories(url)
    doc = Nokogiri::HTML(open(url))
    next_page = doc.at_css('div.pagination-older a')
    stories = doc.css('li.postWrapper')
    stories.each do |story|
      title = story.at_css('h2').text
      content = story.at_css('div.post p').text
      rating_text = story.at_css('div.ratingtext')
      rating = rating_text.gsub('Rating: ', '').gsub('/', '')

      begin
        story = Story.create(title: title, content: content, rating: rating.to_f)
        puts "Story: #{story.id}"
      rescue
        puts 'ERROR!!!!'
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.page(params[:page]).per(10)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  def random
    story = Story.all.sample
    render json: story
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<main class="content" role="main" xmlns="http://www.w3.org/1999/html">
  <div class="panel"></div>
  <div class="pagination-wrapper">
    <nav class="pagination" role="pagination">
      <%= paginate @stories %>
    </nav>
  </div>
  <% @stories.each do |story| %>
      <a href="<%= (url_for [story]) %>" style="text-decoration:none">
        <article class="post tag-superb tag-about-theme tag-information odd">
          <div class="post-inner">
            <header class="post-header">
              <h2 class="post-title"><%= story.title %></h2>
            </header>

            <section class="post-excerpt">
              <p><%= truncate(story.content, length: 80) %></p>
            </section>

					<span class="post-meta">
						<span></span>
						<span><%= story.rating %>&nbspout of 10</span>
						<span></span>
					</span>
          </div>
        </article>
      </a>
  <% end %>
  <div class="pagination-wrapper">
    <nav class="pagination" role="pagination">
      <%= paginate @stories %>
    </nav>
  </div>
</main>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<main class="content" role="main" xmlns="http://www.w3.org/1999/html">
  <div class="panel">

  </div>

  <article class="post tag-superb tag-about-theme tag-information odd">
    <div class="post-inner">
      <header class="post-header">
        <h2 class="post-title"><%= @story.title %></h2>
      </header>

      <section class="post-excerpt">
        <p><%= @story.content %></p>
      </section>

					<span class="post-meta">
						<span></span>
						<span>
              <div class="fb-share-button" data-href="https://twolinestories.herokuapp.com/stories/<%= @story.id %>" data-layout="button"></div>
              <div><%= link_to "Back", root_path %></div>
            </span>
						<span></span>
					</span>
    </div>
  </article>
</main>